name: CI-CD-first-test

env:
  APPLICATION_NAME: "first_application"
  PACKAGE_NAME: "first_package_ver-${{github.sha}}"

on:
  push:
    branches: 
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "hello world from first"

      - name: second name
        run: |
          echo "first message"
          echo "send message"
          echo "application name: ${{ env.APPLICATION_NAME }}"

      - name: git clone
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la



  second_job:
    needs: [first_job]
    env:
      PRIVATE_ENV_FIRST: "private_env first"
      PRIVATE_ENV_SECOND: "private_env second"
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "hello world from second"

      - name: Second name for second job
        run: echo "package name is ${{ env.PACKAGE_NAME }}"

      - name: git
        run: sudo apt install git -y

      - name: print_private_env
        run: |
          echo "first-${{ env.PRIVATE_ENV_FIRST }}"
          echo "second-${{ env.PRIVATE_ENV_SECOND }}"